name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:

    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip list
    - name: Build Jekyll Template
      run: |
        jupyter-book build docs/
    - name: Build HTML
      continue-on-error: true
      run: |
        docker run --rm --security-opt label:disable -v $PWD/docs:/srv/jekyll -u 1000:1000 --entrypoint "/bin/bash" emdupre/jupyter-book -c "bundle install && bundle exec jekyll build && ls -l docs"
    - name: Push to Docs branches
      run: |
        ls -l docs
        ghp-import -p -n -f docs/_site
