name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GH_PYTHON_VERSION: 3.7

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ env.GH_PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.GH_PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip list

    - name: Copy hep_tables notebooks
      run: |
        git clone https://github.com/gordonwatts/hep_tables.git
        cp hep_tables/notebooks/*.ipynb docs/features
        rm -rf hep_tables/
        ls docs/features

    - name: Build Jekyll Template
      run: |
        jupyter-book build docs/
        ls -R

    - name: Publish site
      uses: ./actions/jn-build
      with:
        jekyll_src: 'docs/'

    - name: Push to Docs branches
      run: |
        ls -R docs
        ghp-import -p -n -f docs/_site
